server:
  port: 8004
spring:
  application:
    #当前应用名称
    name: bootstrap
    cloud:
      config:
        server:
          git:
            uri: https://gitee.com/smartdt/springcloudconfig.git #配置Git仓库位置。
            searchPaths: config-repo #配置仓库路径下的相对搜索位置，可以配置多个。
            username: username #访问 Git 仓库的用户名。
            password: password #访问 Git 仓库的用户密码。
            label: master #配置仓库的分支
            ###如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写。
