server:
  port: 8888
spring:
  application:
    #当前应用名称
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/huaDemo/config-repo.git #配置Git仓库位置。
          username:  #访问 Git 仓库的用户名。
          password:  #访问 Git 仓库的用户密码。
          default-label: master #配置仓库的分支
          search-paths: '{application}' #配置仓库路径下的相对搜索位置，可以配置多个。
          ###如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写。
eureka:
  instance:
    # 心跳设置，告诉服务器该实例仍在使用
    lease-renewal-interval-in-seconds: 5
    # 告诉服务器如果10秒内未发送任何续约请求，则关闭该客户端
    lease-expiration-duration-in-seconds: 10
    #在注册中心显示ip
    prefer-ip-address: true
    # 将Instance ID设置成IP:端口的形式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8001/eureka/
    # 抓取服务列表
    registry-fetch-interval-seconds: 30