server:
  port: 8001
eureka:
  instance:
    hostname: localhost
    #在注册中心显示ip
    prefer-ip-address: true
    # 将Instance ID设置成IP:端口的形式
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/